### ISSUE TITLE
The globPattern "undefined" did not match any files, so no file updates will be made.

### ISSUE THREAD

**Issue by doughsay** [fenichelar/ember-simple-auth-token#19]
I can't get this to work with the latest ember-cli 0.1.4.  After installing and running the generator I get this:

```
$ ember generate simple-auth-token
version: 0.1.4
valid watchman found, version: [3.0.0]
installing
The globPattern "undefined" did not match any files, so no file updates will be made.
Installing browser packages via Bower...
  cached git://github.com/simplabs/ember-simple-auth-component.git#0.6.7
Installed browser packages via Bower.
```

So no real error there, but there is that warning which is suspicious...

Then when starting the server:

```
File: simple-auth-token/authenticators/token.js
ENOENT, no such file or directory '/Users/chris/personal/ember-jwt/tmp/tree_merger-tmp_dest_dir-KwihtSqx.tmp/simple-auth/authenticators/base.js'
Error: ENOENT, no such file or directory '/Users/chris/personal/ember-jwt/tmp/tree_merger-tmp_dest_dir-KwihtSqx.tmp/simple-auth/authenticators/base.js'
    at Object.fs.statSync (fs.js:695:18)
    at addModule (/Users/chris/personal/ember-jwt/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:94:46)
    at addModule (/Users/chris/personal/ember-jwt/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:143:9)
    at /Users/chris/personal/ember-jwt/node_modules/ember-cli/node_modules/broccoli-es6-concatenator/index.js:59:7
    at $$$internal$$tryCatch (/Users/chris/personal/ember-jwt/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:470:16)
    at $$$internal$$invokeCallback (/Users/chris/personal/ember-jwt/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:482:17)
    at $$$internal$$publish (/Users/chris/personal/ember-jwt/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:453:11)
    at $$rsvp$asap$$flush (/Users/chris/personal/ember-jwt/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1531:9)
    at process._tickCallback (node.js:419:13)
```

Am I guessing correctly that the generator was supposed to add something to one of the core files?  If so, what?

Note: this was a cleanly generated new ember-cli project, no other customization added.

**Comment by doughsay** [comment]
Sorry, I seem to have jumped the gun on this one.  I guess it should have been obvious, but I didn't realize this package required ember-cli-simple-auth to work.  After installing it correctly, things work just fine.

**Comment by jpadilla** [comment]
@doughsay would changing the installation section to something like this help?

Install [ember-cli-simple-auth](https://github.com/simplabs/ember-cli-simple-auth)

```
npm install --save-dev ember-cli-simple-auth
ember generate ember-cli-simple-auth
```

Install ember-cli-simple-auth-token

```
npm install --save-dev ember-cli-simple-auth-token
ember generate simple-auth-token
```

**Comment by doughsay** [comment]
Thanks, it probably would have helped me, but again, I feel like I probably should have noticed to begin with.  It's relatively obvious already. :)
