### ISSUE TITLE
fastboot error on makeRequest

### ISSUE THREAD

**Issue by tarponjargon** [fenichelar/ember-simple-auth-token#202]
I'm getting a strange fastboot error in the console, having to do with the refreshToken:

```
There was an error running your app in fastboot. More info about the error:
 TypeError: Cannot read property 'ajax' of undefined
    at Class.
 (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:89759:33)
    at /Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:89691:16
    at initializePromise (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:61474:7)
    at new Promise (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:61962:33)
    at Class.refreshAccessToken (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:89690:14)
    at fn (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:14008:18)
    at invokeWithOnError (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:13439:16)
    at Queue.flush (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:13498:9)
    at DeferredActionQueues.flush (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:13622:15)
    at Backburner.end (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:13692:23)
    at Backburner.run (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:13806:16)
    at Backburner._runExpiredTimers (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:14200:10)
    at Timeout.Backburner._boundRunExpiredTimers [as _onTimeout] (/Volumes/Home/Sites/searchapp/tmp/broccoli_merge_trees-output_path-OKQsBrfr.tmp/fastboot/vendor.js:13661:11)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```
It looks like makeRequest is making an ajax request with jquery.  Not sure if there's an issue with my setup or if maybe there's a workaround.  Oddly, the error shows only occasionally in the console, not on every token refresh.

I have ember-simple-auth set to use CookieStore, and am using the latest esat from git.

**Comment by jpadilla** [comment]
This might be fixed in master.
