### ISSUE TITLE
server crash when using JWT with fastboot

### ISSUE THREAD

**Issue by khaled-s** [fenichelar/ember-simple-auth-token#332]
getting an error when refresh token is acquiring a new token from the server after the page is refreshed
```
/tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:15485
        throw new Error(`Assertion Failed: ${desc}`);
              ^

Error: Assertion Failed: calling set on destroyed object: <front@session:main::ember263>.isAuthenticated = true
    at assert (/tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:15485:15)
    at set (/tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:8963:49)
    at /tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:9267:9
    at changeProperties (/tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:7751:7)
    at setProperties (/tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:9264:5)
    at Proxy.setProperties (/tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:20817:40)
    at Proxy._setup (webpack://__ember_auto_import__/./node_modules/ember-simple-auth/dist/initializers/setup-session.js?:20:3060)
    at Proxy._onSessionDataUpdated (webpack://__ember_auto_import__/./node_modules/ember-simple-auth/dist/initializers/setup-session.js?:20:4569)
    at sendEvent (/tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:7397:14)
    at Class.trigger (/tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:18383:28)
    at /tmp/broccoli-2752446XwywZ4qYaaAa/out-582-broccoli_merge_trees/assets/vendor.js:112557:14
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```
I'm using ember with fastboot

ember: 4.12.3
ember-simple-auth: 6.0.0
ember-simple-auth-token: 5.3.2

**Comment by fenichelar** [comment]
ember@4 is not supported at this time but will be soon.
